### ISSUE TITLE
Github complains about Node 12

### ISSUE THREAD

**Issue by flatsiedatsie** [bruceadams/get-release#27]
Firstly, thank you for creating this actions, it's very useful.

However, recently I'm seeing a message on Github that `Node.js 12 actions are deprecated`. Will this action be updated or do you recommend using another one?

Example:
https://github.com/createcandle/candle-weather/actions/runs/3297038736

**Comment by bruceadams** [comment]
Thanks for the note! I just release [v1.3.0](https://github.com/bruceadams/get-release/releases/tag/v1.3.0) updated to run on node16 instead of node12. Can you give it a try and let me know if this successfully addresses the warning message you were seeing?

**Comment by flatsiedatsie** [comment]
It works, but it still complains that `set-output` is deprecated:

```
[get-release](https://github.com/createcandle/candle-weather/actions/runs/3309931397/jobs/5463596329#step:2:11)
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by bruceadams** [comment]
Yikes! I botched the release for v1.3.0! I didn't build `dist/index.js` with the updated dependencies, which means it wasn't really using the newer `@actions/core`. This is fixed in `get-release` v1.3.1.

**Comment by flatsiedatsie** [comment]
Now I'm seeing another error:

```
[get-release](https://github.com/createcandle/candle-weather/actions/runs/3313802669/jobs/5472265098#step:2:16)
GitHub is not a constructor
```

**Comment by bruceadams** [comment]
Oh, my. Sorry about all of this! The update to @actions/github has breaking changes (it was a big update). I think I have adjusted the code correctly in v1.3.2. Unfortunately, I don't have a readily available mechanism for testing this. Are you willing to give it another go an let me know? Thanks for being patient with me!

**Comment by flatsiedatsie** [comment]
No worries, I'm happy to test it.

Speaking of which, I'm still seeing (slightly different) warnings:
https://github.com/createcandle/candle-weather/actions/runs/3324887415

**Comment by flatsiedatsie** [comment]
Any thoughts on the remaining warning?

**Comment by bruceadams** [comment]
Sorry I didn't reply earlier. The error message from GitHub Actions points to a bunch of things, but no longer [get-release](https://github.com/bruceadams/get-release). I'm pretty sure [get-release](https://github.com/bruceadams/get-release) is not implicated in these warnings. I suspect updating the versions of the several actions named will at least reduce and maybe even eliminate the warnings.

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-python, actions/upload-release-asset, actions/upload-release-asset, actions/setup-python, actions/checkout

**Comment by flatsiedatsie** [comment]
Thanks, you were right I think. I asumed the official Github actions would auto-update, but they don't.
